build:
  version: "1.0"

spring:
  datasource:
    url: jdbc:mysql://microservices.c7kaekmmqyel.us-east-2.rds.amazonaws.com/microservices
    username: admin
    password: adminadmin
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

accounts:
  message: "Welcome to accounts service - Production Env"
  contactDetails:
    name: "Ulises GC Prod - Lead"
    email: "ugarciacalderon@gmail.com"
  onCallSupport:
    - 1000238123
    - 5631354654
