build:
  version: "1.0"

spring:
  datasource:
    url: jdbc:mysql://microservices.c7kaekmmqyel.us-east-2.rds.amazonaws.com/microservices
    username: admin
    password: adminadmin
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true


accounts:
  message: "Welcome to accounts service - Development Env"
  contactDetails:
    name: "Ulises GC - Developer"
    email: "ugarciacalderon@gmail.com"
  onCallSupport:
    - "7321738123"
    - "3214354654"
