build:
  version: "2.0"

spring:
  datasource:
    url: jdbc:mysql://microservices.c7kaekmmqyel.us-east-2.rds.amazonaws.com/microservices
    username: admin
    password: adminadmin
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

loans:
  message: "Welcome to loans service - Development Env"
  contactDetails:
    name: "Ulises GC Prod - Lead"
    email: "ugarciacalderon@gmail.com"
  onCallSupport:
    - 1000238123
    - 5631354654
